import { MySelect } from '@src/App';
import { isLocal } from '@src/utils';
import { Button, Form, Input, Modal, Select } from 'antd';
import { useEffect, useState } from 'react';
import { useSelector } from 'react-redux';
import { userInfoR } from '../../store/baseSlice';
const lists: any = [
  {
    appSystemNameCN: '公司官网',
    appSystemNameEN: ' Corporate Website',
    appSystemOwner: '张梦诗',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0001',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '旧360直销商城 ',
    appSystemNameEN: 'Allianz360',
    appSystemOwner: '凡先军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0002',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '2C服务平台（客户服务小程序） ',
    appSystemNameEN: 'namespace：ins-ssp',
    appSystemOwner: '李博',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0003',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '渠道服务平台',
    appSystemNameEN: 'Parter Portal',
    appSystemOwner: '梁泽鸿,冯安',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0004',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: 'OPUS-eMotor',
    appSystemNameEN: '',
    appSystemOwner: '黎飞辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-1',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'OPUS-eClaim',
    appSystemNameEN: '',
    appSystemOwner: '黎飞辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-2',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'OPUS-ePolicy',
    appSystemNameEN: '',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-3',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: 'OPUS-iClaim',
    appSystemNameEN: '',
    appSystemOwner: '刘辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-4',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'OPUS-Pearl',
    appSystemNameEN: '',
    appSystemOwner: '王瑞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-5',
    productManager: '高蕾',
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'OPUS-FA Portal',
    appSystemNameEN: '',
    appSystemOwner: '陈嘉颖',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-6',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'OPUS-eMarine',
    appSystemNameEN: '',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-7',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '旧电子单证平台-Indigo',
    appSystemNameEN: 'OPUS-Indigo',
    appSystemOwner: '黄海芳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-8',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'OPUS-IG_ePolicy',
    appSystemNameEN: '',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-9',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: 'OPUS-IG_ePolicyAdapter',
    appSystemNameEN: '',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0005-10',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '财务系统 ',
    appSystemNameEN: 'Sun Account',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0006',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '增值税管理 ',
    appSystemNameEN: 'VMS',
    appSystemOwner: '陈嘉颖',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0007',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '呼叫中心CRM系统（过河兵）',
    appSystemNameEN: 'CRM',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0008',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '车险网销CRM系统（过河兵）',
    appSystemNameEN: 'ins-cxwx',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0008-2',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '影像系统',
    appSystemNameEN: 'Imaging',
    appSystemOwner: '王瑞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0009',
    productManager: '高蕾',
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'Cognos报表系统',
    appSystemNameEN: 'Cognos',
    appSystemOwner: '王洪国,陈阳明',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0010',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '保单登记平台 ',
    appSystemNameEN: '保单登记平台 ',
    appSystemOwner: '王洪国,卜康亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0011',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: 'OA系统',
    appSystemNameEN: 'OA',
    appSystemOwner: '赵桐,张欢',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0012',
    productManager: '赵桐',
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: '意健险平台',
    appSystemNameEN: '意健险平台',
    appSystemOwner: '王洪国,卜康亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0013',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '保险万事通平台',
    appSystemNameEN: '保险万事通平台',
    appSystemOwner: '王洪国,卜康亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0014',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '统信报表平台',
    appSystemNameEN: '统信报表平台',
    appSystemOwner: '王洪国,卜康亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0015',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '新非车-产品工厂',
    appSystemNameEN: '-',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0016',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '新非车-承保',
    appSystemNameEN: '-',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0017',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '新非车-理赔',
    appSystemNameEN: ' allclaim',
    appSystemOwner: '刘凯星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0018',
    productManager: '刘凯星',
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新非车-再保',
    appSystemNameEN: ' ',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0019',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新非车-收付',
    appSystemNameEN: ' ',
    appSystemOwner: '王绪凯',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0020',
    productManager: '王绪凯',
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '销管',
    appSystemNameEN: ' ',
    appSystemOwner: '林扬,刘辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0021',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'ECIF客户信息管理',
    appSystemNameEN: ' ',
    appSystemOwner: '凡先军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0022',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '电子档案管理',
    appSystemNameEN: 'ins-core-eams',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0023',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '应用网关APIS',
    appSystemNameEN: ' ',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0024',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '电子单证平台',
    appSystemNameEN: '非车 Indigo\nins-core-indigo',
    appSystemOwner: '黄海芳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0025',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新影像系统',
    appSystemNameEN: 'New Image',
    appSystemOwner: '王瑞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0026',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'iLog规则引擎',
    appSystemNameEN: 'iLog',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0027',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '人事管理系统',
    appSystemNameEN: 'HRIS',
    appSystemOwner: '赵桐',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0028',
    productManager: '赵桐',
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: '全面预算系统',
    appSystemNameEN: 'Budget-Plan',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0029',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '高端健康险业务处理子系统',
    appSystemNameEN: ' ',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0030',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '精算系统',
    appSystemNameEN: ' ',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0031',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '邮件系统',
    appSystemNameEN: ' ',
    appSystemOwner: '刘云安',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0032',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '技术基础服务',
    appSystemNameEN: 'ins-comm',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0034',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '大数据定价服务',
    appSystemNameEN: 'ins-ai-nova',
    appSystemOwner: '刘艺飞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0035',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '车险网销平台',
    appSystemNameEN: 'ins-auto-center',
    appSystemOwner: '孙常娜',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0036',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '弹性福利平台（已下线）',
    appSystemNameEN: 'FLEXFULI',
    appSystemOwner: '李晓文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0037',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '来保啦',
    appSystemNameEN: 'clients-c2c-manager',
    appSystemOwner: '蒋佳辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0038',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '商家险(商家后台及后管)',
    appSystemNameEN: 'businessService',
    appSystemOwner: '侯亚东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0039',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '收银台',
    appSystemNameEN: 'ins-cashier',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0040',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '中间网关',
    appSystemNameEN: 'channelService',
    appSystemOwner: '李梦佳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0041',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '京me（员福）',
    appSystemNameEN: 'ins-claim',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0043',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '风控系统',
    appSystemNameEN: 'ins-prism',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0044-01',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '风控系统后管',
    appSystemNameEN: 'ins-prism-dashboard',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0044-02',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '服务管理平台',
    appSystemNameEN: 'smpService',
    appSystemOwner: '李梦佳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0045',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '京东安联财险小程序',
    appSystemNameEN: 'ins-user-interfaces',
    appSystemOwner: '凡先军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0046',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: 'B2C平台',
    appSystemNameEN: 'admin-sso-login',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0047',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '智能理赔系统-EAI',
    appSystemNameEN: 'eai-tuomin-znlp',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0048',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '风控-甲状腺\n已下线',
    appSystemNameEN: 'fengkong-jiazhuangxian',
    appSystemOwner: '王屹岩',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0049',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '标签系统',
    appSystemNameEN: 'ins-bdg-northstar',
    appSystemOwner: '马征',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0052',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: 'AI展示平台',
    appSystemNameEN: 'ins-bdg-vision-pd',
    appSystemOwner: '刘艺飞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0053',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '车险H5图像验证码识别',
    appSystemNameEN: 'ins-bdg-vision-carins',
    appSystemOwner: '刘艺飞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0054',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '碎屏图片AI识别',
    appSystemNameEN: 'ins-bdg-vision-mq',
    appSystemOwner: '刘艺飞',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0055',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '诉讼保全小程序',
    appSystemNameEN: ' ',
    appSystemOwner: '梁泽鸿',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0059',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '碎管系统',
    appSystemNameEN: ' ins-core-fragins',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0061',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '投资一体化系统',
    appSystemNameEN: ' ',
    appSystemOwner: '杨婷婷',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0062',
    productManager: null,
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: '融合平台（京喜系统）',
    appSystemNameEN: ' ',
    appSystemOwner: '姚思恺',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0063',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '车险网销外呼系统',
    appSystemNameEN: ' ',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0064',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '旧智能客服（言犀）',
    appSystemNameEN: ' ',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0065-1',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新智能客服平台-CRM',
    appSystemNameEN: 'CRM',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0065-2',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '理赔电子化系统 （SAAS）',
    appSystemNameEN: ' ',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0066',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '芸客CRM(京东零售-SaaS)',
    appSystemNameEN: ' ',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0068',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'EOS开发质量管理平台',
    appSystemNameEN: 'EOS',
    appSystemOwner: '张金立',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0069',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'MSTR数据可视化系统',
    appSystemNameEN: 'MSTR',
    appSystemOwner: '王洪国,陈阳明',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0070',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '可回溯平台',
    appSystemNameEN: ' ',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0071',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '代码审计系统',
    appSystemNameEN: ' ',
    appSystemOwner: '李学良',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0072',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '偿二代',
    appSystemNameEN: ' ',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0074',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '合和OCR识别',
    appSystemNameEN: ' ',
    appSystemOwner: '李万泽',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0075',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '企业员工拼购',
    appSystemNameEN: ' ',
    appSystemOwner: '梁泽鸿',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0077',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '微保赠险对接服务',
    appSystemNameEN: ' ',
    appSystemOwner: '钟玫冰',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0078',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '延保通服务—公众号',
    appSystemNameEN: '3CService',
    appSystemOwner: '李晓文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0079',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '诉责险项目',
    appSystemNameEN: 'lawsuit',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0080',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '用户中心',
    appSystemNameEN: 'userPartner',
    appSystemOwner: '韩春亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0081',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '京东物流线索提报',
    appSystemNameEN: 'clueReport',
    appSystemOwner: '侯亚东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0082',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '京东物流快递小哥',
    appSystemNameEN: 'namespace：ins-open',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0083',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '来保啦（计划下线）',
    appSystemNameEN: ' ',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0084',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '统一登录平台',
    appSystemNameEN: ' ',
    appSystemOwner: '王应策',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0085',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '医保/社保承保系统',
    appSystemNameEN: ' ',
    appSystemOwner: '王屹岩',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0087',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '医保/社保理赔系统\n【已下线】',
    appSystemNameEN: 'siclaim',
    appSystemOwner: '王应策,刘欢',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0088',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '北极星标签管理系统',
    appSystemNameEN: 'ins-bdg-northstar',
    appSystemOwner: '梁泽鸿',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0090',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '车险API场景对接（京东科技车险频道）',
    appSystemNameEN: 'ins-motor-group',
    appSystemOwner: '孙常娜',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0093',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '监管数据标准化报送系统',
    appSystemNameEN: 'EAST',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0094',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '2B服务平台',
    appSystemNameEN: 'ins-business',
    appSystemOwner: '蒋佳辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0097',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '新直销商城',
    appSystemNameEN: 'mall（待定）',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0098',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '风险管理系统',
    appSystemNameEN: ' ',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0099',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '数据采集平台',
    appSystemNameEN: 'DCP（Data collection Platform）',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0100',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '车险自动报价系统',
    appSystemNameEN: 'ins-car-production',
    appSystemOwner: '黎飞辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0101',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: 'AWC China Minisite',
    appSystemNameEN: 'AWC China Minisite',
    appSystemOwner: '陈旭亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0102',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '新智能客服平台-语音系统',
    appSystemNameEN: 'VCS',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0103',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '达达签约服务',
    appSystemNameEN: ' ins-jd-ziying',
    appSystemOwner: '米高扬',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0104',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '天眼ES搜索平台',
    appSystemNameEN: ' ',
    appSystemOwner: '黄杨俊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0105',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '车险快速出单系统',
    appSystemNameEN: ' ',
    appSystemOwner: '高蕾',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0107',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '车险业务中台',
    appSystemNameEN: 'ins-car',
    appSystemOwner: '李万泽,王瑞,黎飞辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0108',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '随车雇主险投保工具',
    appSystemNameEN: '',
    appSystemOwner: '蒋佳辉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0120',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '测试工具系统\n',
    appSystemNameEN: 'inone',
    appSystemOwner: '刘军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0121',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '服务统一管理平台',
    appSystemNameEN: 'ins-usms',
    appSystemOwner: '黄杨俊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0122',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '态势感知系统',
    appSystemNameEN: '',
    appSystemOwner: '轩志民',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0123',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '主机安全系统',
    appSystemNameEN: '',
    appSystemOwner: '李学良',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0124',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '京东安联导航门户',
    appSystemNameEN: 'jdaz-portal',
    appSystemOwner: '尹佳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0125',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新智能客服平台-在线客服',
    appSystemNameEN: 'jimi-talk',
    appSystemOwner: '黄嘉文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0127',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '新电子单证系统',
    appSystemNameEN: 'edoc',
    appSystemOwner: '蒋信',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0128\n',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '投资系统',
    appSystemNameEN: '',
    appSystemOwner: '杨婷婷',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0129',
    productManager: null,
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: '估值系统',
    appSystemNameEN: '',
    appSystemOwner: '杨婷婷',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0130',
    productManager: null,
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: '信评系统',
    appSystemNameEN: '',
    appSystemOwner: '杨婷婷',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0131',
    productManager: null,
    technicalDepartment: '技术平台部-产品运营支持部',
  },
  {
    appSystemNameCN: 'BI可视化工具',
    appSystemNameEN: 'JdazBI',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0132',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '网关系统统一后管',
    appSystemNameEN: 'Euler-System',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0133',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '水滴渠道网关',
    appSystemNameEN: 'ins-product-bdd',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0134',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '短信平台',
    appSystemNameEN: '',
    appSystemOwner: '尹佳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0135',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '安全扫描系统',
    appSystemNameEN: '',
    appSystemOwner: '黄睿',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0136',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '售卖运营管理系统',
    appSystemNameEN: 'ybgl',
    appSystemOwner: '李晓文',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0137',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '信保系统',
    appSystemNameEN: 'ins-credit',
    appSystemOwner: '边东雪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0138',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '津投商家险系统',
    appSystemNameEN: 'ins-product-jdjr',
    appSystemOwner: '李梦佳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0139',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-支付宝(蚂蚁)',
    appSystemNameEN: 'OPUS-IG_Ant',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-1',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-飞猪',
    appSystemNameEN: 'OPUS-IG_Alitrip',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-2',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-淘宝',
    appSystemNameEN: 'OPUS-IG_Taobao',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-3',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-携程',
    appSystemNameEN: 'OPUS-IG_Ctrip',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-4',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-京东',
    appSystemNameEN: 'OPUS-IG_JD',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-5',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-去哪儿',
    appSystemNameEN: 'OPUS-IG_Qunar',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-6',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-京东thirdp',
    appSystemNameEN: 'OPUS-IG_JD_thirdp',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-7',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-滴滴',
    appSystemNameEN: 'OPUS-IG_Didi',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-8',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '定制化出单接口-途牛',
    appSystemNameEN: 'OPUS-IG_TuNiu',
    appSystemOwner: '吴志强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0140-9',
    productManager: null,
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '津投渠道网关-前置',
    appSystemNameEN: 'ins-travel-api',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0141-01',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '津投渠道网关-处理服务1',
    appSystemNameEN: 'ins-blue',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0141-02',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '津投渠道网关-处理服务2',
    appSystemNameEN: 'ins-gravity',
    appSystemOwner: '刘冉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0141-03',
    productManager: '刘冉',
    technicalDepartment: '技术平台部-互联网商险研发部',
  },
  {
    appSystemNameCN: '数据同步系统-一期、有孚',
    appSystemNameEN: 'flinkx',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0142',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '数据同步系统（有孚）',
    appSystemNameEN: 'flinkx',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0142-2',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '智能保顾微信网销系统（小帮）',
    appSystemNameEN: 'E-Marketing-Wechat',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0143',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '深信服上网行为统一管理平台',
    appSystemNameEN: 'AC',
    appSystemOwner: '周杉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0144',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'JSF代理网关',
    appSystemNameEN: 'ins-channel-jsf',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0145',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: 'Oracle数仓',
    appSystemNameEN: 'Oracle datawarehouse',
    appSystemOwner: '王洪国',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0148',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '大数据数仓平台',
    appSystemNameEN: 'big data warehouse',
    appSystemOwner: '王洪国',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0149',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '商城VPC代理网关',
    appSystemNameEN: 'ins-azcn-api-proxy',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0150',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: 'NF1应用安全网关（测试）',
    appSystemNameEN: 'NF1（WAF）',
    appSystemOwner: '轩志民',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0151',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '服务代理/适配（third-adapter-service）',
    appSystemNameEN: 'third-adapter-service',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0152',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '保顾线索挖掘系统',
    appSystemNameEN: 'ins-consultant',
    appSystemOwner: '马征',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0153',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '反洗钱系统',
    appSystemNameEN: 'aml-insurance',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0154',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'AI验机-手机碎屏识别',
    appSystemNameEN: 'ins-bdg-vision-phone-mq',
    appSystemOwner: '刘艺飞,王维来',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0155',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '运维监控系统',
    appSystemNameEN: '',
    appSystemOwner: '李真真',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0156',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '保顾（企业微信）消息归档',
    appSystemNameEN: 'ins-marketing-qywx',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0157',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '精友定核损系统',
    appSystemNameEN: 'jy assess sys',
    appSystemOwner: '陈旭亮',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0158',
    productManager: null,
    technicalDepartment: '技术平台部-车险研发部',
  },
  {
    appSystemNameCN: '数据接口服务系统',
    appSystemNameEN: 'jdaz-data-svc',
    appSystemOwner: '张燕',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0159',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '春晚活动',
    appSystemNameEN: 'ins-cw-2021-m',
    appSystemOwner: '孙鹏',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0160',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '邮件归档系统',
    appSystemNameEN: 'Softnext MAE',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0161',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'AD域',
    appSystemNameEN: 'Active Directory',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0162',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '安联AD密码自助平台',
    appSystemNameEN: 'ADR',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0163',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'AirWatch MDM',
    appSystemNameEN: 'AirWatch MDM',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0164',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '安联邮件网关',
    appSystemNameEN: 'Softnext Mail Gateway',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0165',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'WSUS & SCCM',
    appSystemNameEN: 'WSUS & SCCM',
    appSystemOwner: '赵家豪',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0166',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '容器集群管理系统',
    appSystemNameEN: 'rancher',
    appSystemOwner: '谭庭伟',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0167',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '基础数据服务',
    appSystemNameEN: 'base data service',
    appSystemOwner: '韩小强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0168',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '新直销商城-留资活动',
    appSystemNameEN: 'ins-activity-custom',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0098-1',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '可回溯后台管理系统',
    appSystemNameEN: 'ins-trace-cms（待定）',
    appSystemOwner: '任永强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0170',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '京me-OA融合',
    appSystemNameEN: 'ins-ime',
    appSystemOwner: '黄杨俊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0171',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '可回溯（自建）',
    appSystemNameEN: 'ins-traceable',
    appSystemOwner: '赵日成',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0172',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '保ME-测评服务',
    appSystemNameEN: 'ins-baome',
    appSystemOwner: '孙鹏',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0173',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '杀毒软件管理平台',
    appSystemNameEN: 'anti-virus',
    appSystemOwner: '周杉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0174',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '统一运维平台',
    appSystemNameEN: 'cmdb',
    appSystemOwner: '高明,张雨晨',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0175',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'KMS激活服务器',
    appSystemNameEN: 'KMS',
    appSystemOwner: '周杉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0176',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '被保人授权服务',
    appSystemNameEN: '',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0177',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '偿二代二期',
    appSystemNameEN: 'ins-srm-cross-production',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0178',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '打印服务器',
    appSystemNameEN: 'PrintServer',
    appSystemOwner: '周杉',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0179',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '智策系统',
    appSystemNameEN: '',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0113',
    productManager: '赵英楠',
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: 'EasyMock系统',
    appSystemNameEN: 'EasyMock',
    appSystemOwner: '刘军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0212',
    productManager: '李真真',
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '大数据任务调度平台',
    appSystemNameEN: '',
    appSystemOwner: '韩小强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0213',
    productManager: '赵英楠',
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '数据迁移',
    appSystemNameEN: '',
    appSystemOwner: '王应策',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0214',
    productManager: '王静怡',
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'ACES加密系统',
    appSystemNameEN: 'ACES',
    appSystemOwner: '李学良',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0111',
    productManager: '李学良',
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: 'pp系统',
    appSystemNameEN: '',
    appSystemOwner: '王应策',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0112',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: 'UMP服务代理',
    appSystemNameEN: 'ins-ump-proxy',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0181',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '承保交易系统',
    appSystemNameEN: 'ins-core-fragins',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0182',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '数据分类分级系统',
    appSystemNameEN: 'flfj',
    appSystemOwner: '李学良',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0184',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '用户中心-客户模块-接口服务',
    appSystemNameEN: 'ins-user-customer-app',
    appSystemOwner: '李刚',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0081-7',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '托管区硬件监控平台',
    appSystemNameEN: 'JDconsole',
    appSystemOwner: '赵阳',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0185',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '元数据管理平台',
    appSystemNameEN: 'ins-bigdata-metadata',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0186',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '自动化测试系统',
    appSystemNameEN: '',
    appSystemOwner: '刘军',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0183',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'sonar代码扫描系统',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0089',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'SunGL自动导入系统',
    appSystemNameEN: 'gl-sun-auto-import',
    appSystemOwner: '黄启星',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0187',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '统一任务调度平台（xxl-job）升级版',
    appSystemNameEN: 'xxl-job-admin',
    appSystemOwner: '黄杨俊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0188',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '数据提取平台',
    appSystemNameEN: 'ins-data-collection',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0189',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '后台管理公共UI组件库',
    appSystemNameEN: 'public-management-ui',
    appSystemOwner: '安顺利',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0190',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '营销系统（短信群发）',
    appSystemNameEN: 'ins-user-sms',
    appSystemOwner: '陈庚',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0191',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '意健险PBM项目',
    appSystemNameEN: 'ins-pbm',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0192',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: 'ToC销售平台',
    appSystemNameEN: 'ins-toc-cms/user-partner',
    appSystemOwner: '任永强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0193',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '车险测试数据管理平台',
    appSystemNameEN: 'auto_test_platform',
    appSystemOwner: '王宏伟',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0194',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '数据加工平台',
    appSystemNameEN: 'ins-bigdata-easydata',
    appSystemOwner: '卫东',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0195',
    productManager: null,
    technicalDepartment: '技术平台部-数据平台开发部',
  },
  {
    appSystemNameCN: '安全漏扫系统',
    appSystemNameEN: 'Qualys',
    appSystemOwner: '王宇平',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0197',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '统一日志表迁移系统',
    appSystemNameEN: 'ins-common-log',
    appSystemOwner: '黄杨俊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0198',
    productManager: null,
    technicalDepartment: '技术平台部-运营研发部',
  },
  {
    appSystemNameCN: '承保规则引擎服务',
    appSystemNameEN: 'ins-core-prodfactory',
    appSystemOwner: '龚如阁',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0199',
    productManager: null,
    technicalDepartment: '技术平台部-承保研发部',
  },
  {
    appSystemNameCN: '统一测试管理平台',
    appSystemNameEN: 'allianztest',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0200',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '发布系统3.0-XBP交互系统',
    appSystemNameEN: 'ins-devops-xbpapp-production',
    appSystemOwner: '谭庭伟',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0201',
    productManager: null,
    technicalDepartment: '技术平台部-基础技术部',
  },
  {
    appSystemNameCN: '商城域sonar代码扫描',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0202',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'jdstack域sonar代码扫描',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0203',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '测试管理系统',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0204',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'mock系统',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0205',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: 'jdstack域sonar代码扫描-预发环境',
    appSystemNameEN: '',
    appSystemOwner: '张新磊',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0206',
    productManager: null,
    technicalDepartment: '技术平台部-研发质量部',
  },
  {
    appSystemNameCN: '官网后台管理系统',
    appSystemNameEN: 'user-partner',
    appSystemOwner: '任永强',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0210',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
  {
    appSystemNameCN: '灰度配置中心',
    appSystemNameEN: 'ins-gray',
    appSystemOwner: '朱海申',
    businessDepartment: null,
    businessOwner: null,
    description: '',
    id: 'JDAZ-0211',
    productManager: null,
    technicalDepartment: '技术平台部-直销意健险研发部',
  },
];

export const AboutComponent: any = () => {
  const userInfo: any = useSelector(userInfoR);
  if (isLocal()) {
    console.log(1);
  }
  const [ModalForm] = Form.useForm();
  const [ModalForm2] = Form.useForm();
  const [isVisible, isVisibleSet] = useState<boolean>(false);
  const [sysList, sysListSet] = useState<any[]>([]);

  useEffect(() => {
    console.log('about');
    sysListSet(lists);
    ModalForm2.setFieldsValue({
      subSystemNameCN: '新非车-产品工厂',
    });
  }, []);
  return (
    <>
      <div
        onClick={() => {
          isVisibleSet(true);
          ModalForm.setFieldsValue({
            subSystemNameCN: '新非车-产品工厂',
          });
        }}
      >
        我是about页面2{JSON.stringify(userInfo)}
      </div>
      <div>
        <MySelect
          // listItemHeight={32}
          // size="large"
          getPopupContainer={(e: any) => e.parentNode}
          showSearch
          value={'新非车-产品工厂'}
          allowClear
          placeholder="请选择"
          optionFilterProp="children"
        >
          {sysList?.map((item: any) => (
            <Select.Option value={item.appSystemNameCN} key={item.appSystemNameCN}>
              {item.appSystemNameCN}
            </Select.Option>
          ))}
        </MySelect>
      </div>
      <Form preserve={false} className="anPopF3orm2" form={ModalForm2} layout="inline">
        <Form.Item
          label="所属系统"
          name="subSystemNameCN"
          rules={[{ required: true, message: '请选择所属系统' }]}
        >
          <Select
            listItemHeight={32}
            showSearch
            allowClear
            placeholder="请选择"
            optionFilterProp="children"
          >
            {sysList?.map((item: any) => (
              <Select.Option value={item.appSystemNameCN} key={item.appSystemNameCN}>
                {item.appSystemNameCN}
              </Select.Option>
            ))}
          </Select>
        </Form.Item>
      </Form>

      <Modal
        width={500}
        className="scroll"
        destroyOnClose={true}
        keyboard={false}
        maskClosable={false}
        title="asd"
        open={isVisible}
        onCancel={() => {
          isVisibleSet(false);
        }}
        footer={[
          <Button
            key={21}
            danger
            style={{ marginRight: '32px' }}
            onClick={() => {
              isVisibleSet(false);
            }}
          >
            取消
          </Button>,
          <Button
            key={1}
            type="primary"
            danger
            onClick={() => {
              console.log(1);
            }}
          >
            确定
          </Button>,
        ]}
      >
        <Form preserve={false} className="anPopF3orm2" form={ModalForm} layout="inline">
          <Form.Item
            label="所属系统"
            name="subSystemNameCN"
            rules={[{ required: true, message: '请选择所属系统' }]}
          >
            <Select
              listItemHeight={32}
              showSearch
              allowClear
              placeholder="请选择"
              optionFilterProp="children"
            >
              {sysList?.map((item: any) => (
                <Select.Option value={item.appSystemNameCN} key={item.appSystemNameCN}>
                  {item.appSystemNameCN}
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
        </Form>
      </Modal>
    </>
  );
};
